[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm install",
  "python -m pip install --break-system-packages --upgrade pip",
  "python -m pip install --break-system-packages snowflake-connector-python[snowpark]==3.7.0",
  "python -m pip install --break-system-packages cryptography==42.0.5"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
