[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install --break-system-packages snowflake-connector-python[snowpark] cryptography"
]

[start]
cmd = "npm start"
