[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm install",
  "pip install --break-system-packages snowflake-connector-python[snowpark] cryptography"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
