[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs", "npm"]

[phases.install]
cmds = [
  "pip install --break-system-packages snowflake-connector-python[snowpark] cryptography",
  "npm install"
]

[start]
cmd = "npm start"
